// ═══════════════════════════════════════════════════════════════════
//  Search Index — فهرس البحث الشامل
//  يحتوي على كل الحاسبات والعدادات والمقالات والصفحات
//  مع كلمات مفتاحية ومرادفات للبحث الذكي
// ═══════════════════════════════════════════════════════════════════

import { ALL_ARTICLES } from "@/lib/blog/articles";

export type SearchItemType = "calculator" | "countdown" | "article" | "page";

export interface SearchItem {
  id: string;
  type: SearchItemType;
  title: string;
  description: string;
  href: string;
  icon: string;
  keywords: string[]; // مرادفات وكلمات مفتاحية للبحث
  category?: string;
}

// ─────────────────────────────────────────────────────────────────
// الحاسبات
// ─────────────────────────────────────────────────────────────────
const CALCULATORS: SearchItem[] = [
  {
    id: "calc-zakat",
    type: "calculator",
    title: "حاسبة الزكاة",
    description: "احسب زكاة المال والذهب والأسهم والتجارة وفق الأحكام الشرعية",
    href: "/calculators/zakat",
    icon: "💰",
    category: "شرعي",
    keywords: ["زكاة", "زكاه", "الزكاة", "زكاة المال", "زكاة الذهب", "زكاة الأسهم", "زكاة التجارة", "نصاب", "زكاه الفطر", "حساب الزكاة", "احسب الزكاة", "كم زكاتي", "zakat"],
  },
  {
    id: "calc-salary",
    type: "calculator",
    title: "حاسبة الراتب",
    description: "احسب صافي راتبك بعد التأمينات والبدلات والاستقطاعات",
    href: "/calculators/salary",
    icon: "💵",
    category: "مالي",
    keywords: ["راتب", "رواتب", "صافي الراتب", "حساب الراتب", "احسب راتبي", "مرتب", "المرتب", "الاجر", "أجر", "تامينات", "تامين اجتماعي", "gosi", "salary"],
  },
  {
    id: "calc-end-of-service",
    type: "calculator",
    title: "حاسبة مكافأة نهاية الخدمة",
    description: "احسب مكافأة نهاية الخدمة وفق نظام العمل السعودي",
    href: "/calculators/end-of-service",
    icon: "📋",
    category: "مالي",
    keywords: ["نهاية الخدمة", "نهايه الخدمه", "مكافأة نهاية الخدمة", "مكافاة", "مكافأة", "استقالة", "فصل", "انهاء عقد", "تسريح", "end of service", "eos"],
  },
  {
    id: "calc-mortgage",
    type: "calculator",
    title: "حاسبة التمويل العقاري",
    description: "احسب القسط الشهري للقرض العقاري ومدته وفوائده",
    href: "/calculators/mortgage",
    icon: "🏠",
    category: "مالي",
    keywords: ["عقاري", "تمويل عقاري", "قرض عقاري", "قرض", "قسط", "اقساط", "رهن", "بيت", "منزل", "سكن الموظفين", "mortgage", "loan"],
  },
  {
    id: "calc-citizen-account",
    type: "calculator",
    title: "حاسبة حساب المواطن",
    description: "احسب استحقاقك من الدعم الشهري لبرنامج حساب المواطن",
    href: "/calculators/citizen-account",
    icon: "👨‍👩‍👧",
    category: "مالي",
    keywords: ["حساب المواطن", "دعم الحكومة", "الدعم", "مواطن", "اهلية حساب المواطن", "استحقاق", "دعم شهري", "citizen account"],
  },
  {
    id: "calc-dependents-fee",
    type: "calculator",
    title: "حاسبة رسوم المرافقين",
    description: "احسب رسوم المرافقين والتابعين الشهرية والسنوية",
    href: "/calculators/dependents-fee",
    icon: "👥",
    category: "مالي",
    keywords: ["مرافقين", "مرافقون", "مرافق", "تابعين", "تابع", "رسوم المرافقين", "رسوم التابعين", "رسوم", "عائلة", "زوجة", "اولاد", "400 ريال", "dependents"],
  },
  {
    id: "calc-labor-fee",
    type: "calculator",
    title: "حاسبة المقابل المالي للعمالة",
    description: "احسب رسوم مكتب العمل للعمالة الوافدة ونسبة السعودة",
    href: "/calculators/labor-fee",
    icon: "🏢",
    category: "مالي",
    keywords: ["مقابل مالي", "المقابل المالي", "رسوم العمالة", "رسوم العمال", "مكتب العمل", "سعودة", "السعودة", "نطاقات", "عمالة وافدة", "700 ريال", "800 ريال", "labor fee", "expat levy"],
  },
  {
    id: "calc-electricity",
    type: "calculator",
    title: "حاسبة فاتورة الكهرباء",
    description: "احسب فاتورة الكهرباء الشهرية وفق الشرائح الجديدة",
    href: "/calculators/electricity",
    icon: "⚡",
    category: "مالي",
    keywords: ["كهرباء", "فاتورة الكهرباء", "استهلاك الكهرباء", "شركة الكهرباء", "se", "electricity", "كيلو واط", "عداد"],
  },
  {
    id: "calc-vat",
    type: "calculator",
    title: "حاسبة ضريبة القيمة المضافة",
    description: "احسب ضريبة القيمة المضافة VAT 15% للفواتير",
    href: "/calculators/vat",
    icon: "🧾",
    category: "مالي",
    keywords: ["ضريبة", "الضريبة", "قيمة مضافة", "القيمة المضافة", "vat", "ضريبه", "15%", "فاتورة ضريبية", "tax"],
  },
  {
    id: "calc-inheritance",
    type: "calculator",
    title: "حاسبة الميراث",
    description: "احسب الميراث الشرعي وفق أحكام الفرائض الإسلامية",
    href: "/calculators/inheritance",
    icon: "📜",
    category: "شرعي",
    keywords: ["ميراث", "ورث", "الميراث", "الارث", "ارث", "فرائض", "تركة", "ورثة", "inheritance", "ميراث الزوجة", "ميراث الاب"],
  },
  {
    id: "calc-bmi",
    type: "calculator",
    title: "حاسبة كتلة الجسم BMI",
    description: "احسب مؤشر كتلة الجسم ووزنك المثالي",
    href: "/calculators/bmi",
    icon: "⚖️",
    category: "صحي",
    keywords: ["bmi", "كتلة الجسم", "مؤشر كتلة الجسم", "الوزن المثالي", "وزن", "سمنة", "نحافة", "طول", "body mass"],
  },
  {
    id: "calc-pregnancy",
    type: "calculator",
    title: "حاسبة الحمل",
    description: "احسب أسابيع الحمل وموعد الولادة المتوقع",
    href: "/calculators/pregnancy",
    icon: "🤰",
    category: "صحي",
    keywords: ["حمل", "الحمل", "حامل", "موعد الولادة", "اسابيع الحمل", "متى ولادتي", "pregnancy", "due date"],
  },
  {
    id: "calc-age",
    type: "calculator",
    title: "حاسبة العمر",
    description: "احسب عمرك بالهجري والميلادي بدقة السنة والشهر واليوم",
    href: "/calculators/age",
    icon: "🎂",
    category: "أدوات",
    keywords: ["عمر", "العمر", "كم عمري", "احسب عمري", "احسب عمرك", "حساب العمر", "تاريخ الميلاد", "ميلاد", "برج", "البرج", "عيد ميلاد", "age calculator"],
  },
  {
    id: "calc-retirement",
    type: "calculator",
    title: "حاسبة التقاعد",
    description: "احسب راتب التقاعد وسنوات الخدمة المطلوبة",
    href: "/calculators/retirement",
    icon: "👴",
    category: "مالي",
    keywords: ["تقاعد", "التقاعد", "معاش", "راتب التقاعد", "متقاعد", "سن التقاعد", "retirement", "pension"],
  },
  {
    id: "calc-budget",
    type: "calculator",
    title: "حاسبة الميزانية الشخصية",
    description: "خطط ميزانيتك الشهرية بقاعدة 50/30/20",
    href: "/calculators/budget",
    icon: "📊",
    category: "مالي",
    keywords: ["ميزانية", "الميزانية", "ميزانيه", "تخطيط مالي", "50/30/20", "مصاريف", "budget", "ادخار"],
  },
  {
    id: "calc-savings",
    type: "calculator",
    title: "حاسبة الادخار",
    description: "احسب مدة وصولك لهدف الادخار مع الفوائد",
    href: "/calculators/savings",
    icon: "🏦",
    category: "مالي",
    keywords: ["ادخار", "الادخار", "توفير", "استثمار", "فائدة", "ربح", "savings", "اهداف"],
  },
  {
    id: "calc-currency",
    type: "calculator",
    title: "حاسبة تحويل العملات",
    description: "حوّل بين الريال السعودي والعملات العالمية",
    href: "/calculators/currency",
    icon: "💱",
    category: "مالي",
    keywords: ["عملات", "تحويل عملات", "دولار", "يورو", "ريال", "درهم", "جنيه", "sar", "usd", "currency"],
  },
  {
    id: "calc-percentage",
    type: "calculator",
    title: "حاسبة النسبة المئوية",
    description: "احسب النسب المئوية والزيادات والخصومات",
    href: "/calculators/percentage",
    icon: "%",
    category: "أدوات",
    keywords: ["نسبة مئوية", "نسبة", "خصم", "زيادة", "percentage", "%"],
  },
  {
    id: "calc-profit-margin",
    type: "calculator",
    title: "حاسبة هامش الربح",
    description: "احسب هامش الربح ونسبة الربحية للمنتجات",
    href: "/calculators/profit-margin",
    icon: "📈",
    category: "مالي",
    keywords: ["ربح", "هامش الربح", "تجارة", "تسعير", "تكلفة", "profit margin"],
  },
  {
    id: "calc-gpa",
    type: "calculator",
    title: "حاسبة المعدل التراكمي GPA",
    description: "احسب معدلك التراكمي الجامعي",
    href: "/calculators/gpa",
    icon: "🎓",
    category: "تعليمي",
    keywords: ["معدل", "معدل تراكمي", "gpa", "جامعة", "طالب", "درجات", "ساعات"],
  },
  {
    id: "calc-time",
    type: "calculator",
    title: "حاسبة الوقت والتاريخ",
    description: "احسب الفرق بين تاريخين أو أضف أياماً لتاريخ",
    href: "/calculators/time",
    icon: "⏱️",
    category: "أدوات",
    keywords: ["وقت", "تاريخ", "الفرق بين تاريخين", "ايام", "اسابيع", "time", "date"],
  },
];

// ─────────────────────────────────────────────────────────────────
// العدادات التنازلية
// ─────────────────────────────────────────────────────────────────
const COUNTDOWNS: SearchItem[] = [
  {
    id: "cd-ramadan",
    type: "countdown",
    title: "عدّاد رمضان",
    description: "كم باقي على شهر رمضان المبارك",
    href: "/countdowns/ramadan",
    icon: "🌙",
    category: "إسلامي",
    keywords: ["رمضان", "شهر رمضان", "كم باقي على رمضان", "متى رمضان", "صوم", "صيام", "رمضان 2026", "ramadan"],
  },
  {
    id: "cd-eid-fitr",
    type: "countdown",
    title: "عدّاد عيد الفطر",
    description: "كم باقي على عيد الفطر المبارك",
    href: "/countdowns/eid-fitr",
    icon: "🎉",
    category: "إسلامي",
    keywords: ["عيد الفطر", "العيد", "عيد", "كم باقي على العيد", "متى العيد", "عيد الفطر 2026", "eid fitr"],
  },
  {
    id: "cd-eid-adha",
    type: "countdown",
    title: "عدّاد عيد الأضحى",
    description: "كم باقي على عيد الأضحى المبارك",
    href: "/countdowns/eid-adha",
    icon: "🐑",
    category: "إسلامي",
    keywords: ["عيد الاضحى", "الاضحى", "اضحى", "عيد الحج", "عيد الكبير", "اضحية", "eid adha"],
  },
  {
    id: "cd-hajj",
    type: "countdown",
    title: "عدّاد الحج",
    description: "كم باقي على موسم الحج",
    href: "/countdowns/hajj",
    icon: "🕋",
    category: "إسلامي",
    keywords: ["حج", "الحج", "موسم الحج", "متى الحج", "مناسك", "منى", "عرفة", "مكة", "hajj"],
  },
  {
    id: "cd-arafah",
    type: "countdown",
    title: "عدّاد يوم عرفة",
    description: "كم باقي على يوم عرفة",
    href: "/countdowns/arafah",
    icon: "⛰️",
    category: "إسلامي",
    keywords: ["عرفة", "يوم عرفة", "وقفة عرفة", "arafah", "arafat"],
  },
  {
    id: "cd-laylatul-qadr",
    type: "countdown",
    title: "عدّاد ليلة القدر",
    description: "كم باقي على ليلة القدر",
    href: "/countdowns/laylatul-qadr",
    icon: "✨",
    category: "إسلامي",
    keywords: ["ليلة القدر", "القدر", "العشر الاواخر", "laylatul qadr"],
  },
  {
    id: "cd-mawlid",
    type: "countdown",
    title: "عدّاد المولد النبوي",
    description: "كم باقي على المولد النبوي الشريف",
    href: "/countdowns/mawlid",
    icon: "🕌",
    category: "إسلامي",
    keywords: ["مولد", "المولد", "المولد النبوي", "مولد الرسول", "mawlid"],
  },
  {
    id: "cd-hijri-new-year",
    type: "countdown",
    title: "عدّاد رأس السنة الهجرية",
    description: "كم باقي على رأس السنة الهجرية",
    href: "/countdowns/hijri-new-year",
    icon: "📅",
    category: "إسلامي",
    keywords: ["راس السنة", "السنة الهجرية", "الهجرة", "محرم", "hijri new year"],
  },
  {
    id: "cd-ashura",
    type: "countdown",
    title: "عدّاد يوم عاشوراء",
    description: "كم باقي على يوم عاشوراء",
    href: "/countdowns/ashura",
    icon: "☪️",
    category: "إسلامي",
    keywords: ["عاشوراء", "محرم", "عاشورا", "ashura"],
  },
  {
    id: "cd-national-day",
    type: "countdown",
    title: "عدّاد اليوم الوطني السعودي",
    description: "كم باقي على اليوم الوطني للمملكة",
    href: "/countdowns/national-day",
    icon: "🇸🇦",
    category: "وطني",
    keywords: ["اليوم الوطني", "اليوم الوطني السعودي", "يوم الوطن", "23 سبتمبر", "السعودية", "national day"],
  },
  {
    id: "cd-foundation-day",
    type: "countdown",
    title: "عدّاد يوم التأسيس",
    description: "كم باقي على يوم التأسيس السعودي",
    href: "/countdowns/foundation-day",
    icon: "⚔️",
    category: "وطني",
    keywords: ["يوم التاسيس", "التاسيس", "22 فبراير", "foundation day"],
  },
  {
    id: "cd-flag-day",
    type: "countdown",
    title: "عدّاد يوم العلم",
    description: "كم باقي على يوم العلم السعودي",
    href: "/countdowns/flag-day",
    icon: "🚩",
    category: "وطني",
    keywords: ["يوم العلم", "العلم السعودي", "flag day"],
  },
  {
    id: "cd-salaries",
    type: "countdown",
    title: "مواعيد الرواتب الحكومية",
    description: "كل مواعيد الرواتب الحكومية في السعودية",
    href: "/countdowns/salaries-dates",
    icon: "💵",
    category: "رواتب",
    keywords: ["مواعيد الرواتب", "موعد الراتب", "الراتب", "راتب الحكومة", "كم باقي على الراتب", "salary dates"],
  },
  {
    id: "cd-citizen-account",
    type: "countdown",
    title: "موعد حساب المواطن",
    description: "كم باقي على موعد إيداع حساب المواطن",
    href: "/countdowns/citizen-account",
    icon: "👨‍👩‍👧",
    category: "رواتب",
    keywords: ["حساب المواطن", "موعد حساب المواطن", "الدعم", "دعم المواطن"],
  },
  {
    id: "cd-social-security",
    type: "countdown",
    title: "موعد الضمان الاجتماعي",
    description: "كم باقي على موعد إيداع الضمان الاجتماعي المطور",
    href: "/countdowns/social-security",
    icon: "🤝",
    category: "رواتب",
    keywords: ["ضمان اجتماعي", "الضمان", "ضمان مطور", "معاش الضمان", "social security"],
  },
  {
    id: "cd-pension",
    type: "countdown",
    title: "موعد رواتب المتقاعدين",
    description: "كم باقي على موعد صرف رواتب التقاعد",
    href: "/countdowns/pension-salaries",
    icon: "👴",
    category: "رواتب",
    keywords: ["رواتب المتقاعدين", "تقاعد", "معاش", "متقاعد", "pension"],
  },
  {
    id: "cd-saned",
    type: "countdown",
    title: "موعد صرف ساند",
    description: "كم باقي على موعد إيداع ساند",
    href: "/countdowns/saned-payment",
    icon: "💼",
    category: "رواتب",
    keywords: ["ساند", "تعويض ساند", "بطالة", "saned"],
  },
  {
    id: "cd-university",
    type: "countdown",
    title: "موعد مكافأة الجامعة",
    description: "كم باقي على صرف مكافأة الجامعيين",
    href: "/countdowns/university-stipend",
    icon: "🎓",
    category: "رواتب",
    keywords: ["مكافاة الجامعة", "مكافاة الطلاب", "جامعة", "طلاب"],
  },
];

// ─────────────────────────────────────────────────────────────────
// صفحات عامة
// ─────────────────────────────────────────────────────────────────
const PAGES: SearchItem[] = [
  {
    id: "page-calculators",
    type: "page",
    title: "جميع الحاسبات",
    description: "استعرض جميع الحاسبات المتوفرة في الموقع",
    href: "/calculators",
    icon: "🧮",
    keywords: ["حاسبات", "كل الحاسبات", "جميع الحاسبات", "قائمة الحاسبات", "calculators"],
  },
  {
    id: "page-countdowns",
    type: "page",
    title: "جميع العدادات التنازلية",
    description: "استعرض جميع العدادات التنازلية",
    href: "/countdowns",
    icon: "⏰",
    keywords: ["عدادات", "كل العدادات", "عداد تنازلي", "countdowns"],
  },
  {
    id: "page-hijri-calendar",
    type: "page",
    title: "التقويم الهجري",
    description: "تحويل التواريخ بين الهجري والميلادي",
    href: "/hijri-calendar",
    icon: "📅",
    keywords: ["هجري", "التقويم الهجري", "تقويم هجري", "تحويل هجري ميلادي", "ام القرى", "hijri", "hijri calendar", "ميلادي"],
  },
  {
    id: "page-blog",
    type: "page",
    title: "المدونة",
    description: "مقالات ودروس شاملة",
    href: "/blog",
    icon: "📚",
    keywords: ["مدونة", "مقالات", "دروس", "blog", "articles"],
  },
  {
    id: "page-about",
    type: "page",
    title: "عن الموقع",
    description: "تعرّف على حاسبة VIP",
    href: "/about",
    icon: "ℹ️",
    keywords: ["عن الموقع", "من نحن", "about"],
  },
  {
    id: "page-contact",
    type: "page",
    title: "اتصل بنا",
    description: "تواصل مع فريق حاسبة VIP",
    href: "/contact",
    icon: "✉️",
    keywords: ["اتصل بنا", "تواصل", "contact"],
  },
];

// ─────────────────────────────────────────────────────────────────
// المقالات (تُحمّل تلقائياً من ALL_ARTICLES)
// ─────────────────────────────────────────────────────────────────
function buildArticleItems(): SearchItem[] {
  return ALL_ARTICLES.map((a) => ({
    id: `article-${a.slug}`,
    type: "article" as const,
    title: a.titleAr,
    description: a.descriptionAr,
    href: `/blog/${a.slug}`,
    icon: a.icon,
    category: a.category,
    keywords: [...a.keywords, a.titleAr],
  }));
}

// ─────────────────────────────────────────────────────────────────
// الفهرس الموحّد
// ─────────────────────────────────────────────────────────────────
export function getSearchIndex(): SearchItem[] {
  return [...CALCULATORS, ...COUNTDOWNS, ...PAGES, ...buildArticleItems()];
}
